### ISSUE TITLE
Ready for use

### ISSUE THREAD

**Issue by brianteeman** [hr-it-solutions/DD_J_com_gmaps_locations_cmty_edit#2]
Is this ready for use yet or is it still work in progress?

**Comment by HRIT-Florian** [comment]
It is alpha and experimental. 
We tested it only in a project under development.
But feel free to use and report bugs without warranty.

**Comment by brianteeman** [comment]
ok will do

**Comment by HRIT-Florian** [comment]
I see a huge of work coming in.

**Comment by brianteeman** [comment]
Tested it locally and functionality all worked

I would suggest changing the layout for the edit form to be a single column only as there is less width in the site template compared to the admin and it results in a messed up display.

The installer obviously needs a little tidying up as it references media folders and sql that are not present and the language files need adding.

All minor things. Otherwise it appeared to work perfectly
